### ISSUE TITLE
Win.Seek("body", 0, io.SeekEnd) always returns 0

### ISSUE THREAD

**Issue by ziutek** [9fans/go#29]
Win.Seek always returns 0  in case of io.SeekEnd, io.SeekCurrent. Does it understand them correctly? 

Is there any other way to get the size of window data in bytes?

I wrote a simple [tool for acme](https://github.com/ziutek/agr) that runs _guru_ on selected entity. It can run different guru commands for three selection kinds: pointing at, select, select before.

The problem is that guru requires byte offsets but Win.ReadAddr returns character offsets (maybe it is guru bug).

I've managed to obtain the required byte offsets of selection but it is based on hack that requires read _data_ from current selection to the end of file and next read the whole _body_.

**Comment by fhs** [comment]
`io.SeekEnd` doesn't work because it's based on the file size returned by stat, which is always 0 in acme file server. See https://github.com/9fans/plan9port/blob/master/src/cmd/acme/fsys.c#L741

A tools like what you're working on already exists: https://github.com/davidrjenni/A .
The [guru docs](https://docs.google.com/document/d/1_Y9xCEMj5S-7rv2ooHpZNH15JgRT5iM742gJkw5LtmQ/edit) lists two other tools ([aw](https://github.com/mjibson/aw) and [gofinder](https://github.com/mpl/gofinder)) but I've never used them.
Also, I'm working on Language Server Protocol tools (see [acme-lsp](https://github.com/fhs/acme-lsp)) which does similar stuff and it'll eventually use the official Go Language Server [golsp](https://godoc.org/golang.org/x/tools/cmd/golsp) when it's ready.

I wish it was easier to find acme tools in github but the usual [acme tag](https://github.com/topics/acme) is littered with Let's Encrypt stuff. I encourage people to use the [acme-text-editor tag](https://github.com/topics/acme-text-editor) instead.

**Comment by ziutek** [comment]
Thanks. I've a solution that works for me but it requires read a whole file almost twice to get the selection position in bytes.

I know about A, but I need simpler tool for only my needs. The goal is to have one short command in Acme tag that can run three guru commands based on how the element is selected.

For example, if you have `fmt.Printf`, you can select it this way:

`fmt.Prin][tf` - simple click in the middle of Printf: agr will run _guru definition_,

`fmt.[Printf] - double click on Printf: agr will run _guru referrers_

`fmt[.Printf]` - select something before Prinft that doesn't contain any letter (can be spaces, tabs, dots, etc.): run another guru  command, preferably less frequently used one.

Maybe this idea will be useful to you.

**Comment by fhs** [comment]
I'm working on something similar acme-lsp, but executing different things based on selection is a bit language dependent. Right now I can execute *completion*, *hover* or *signature help* based on cursor position. I'm still thinking about how to integrate them into one command without assuming the programming language.

We can continue this discussion in this acme-lsp issue if you're interested: https://github.com/fhs/acme-lsp/issues/1
