### ISSUE TITLE
4s hangs on Windows

### ISSUE THREAD

**Issue by mehlon** [9fans/go#9]
When I try to execute `4s` on Windows with `devdraw` from http://sam.cat-v.org/_files/win32_sam.zip, it  hangs and uses up all memory, never creating a new window.

Steps to reproduce:
1. Have `devdraw.exe` in your PATH.
2. `go get 9fans.net/go/games/4s`
3. `%GOPATH%/bin/4s`

**Comment by rsc** [comment]
I am not 100% sure but my guess is that the problem is in the Windows devdraw. That port of sam is somewhat unofficial and may well be out of sync with the main plan9port, which 9fans.net/go/games/4s depends on. There has been talk on plan9port-dev recently about a complete port to Windows. Maybe if that works out, the new devdraw will work better.

Closing this issue because I'm pretty much certain it's not the Go code's problem but instead the stale devdraw. And I don't know how to make a new devdraw on Windows, but I hope the effort I mentioned leads to that.
